import NovedadesItem from "@/components/novedaditems";
export const metadata = {
  title: "Transportes X :: Novedades",
  description: " destacadosGenerated by create next app",
};
export default async function Novedades() {
  const data = await fetch(`${process.env.API_BASE_URL}/api/novedades`, {
    cache: "no-store",
  });

  const novedades = await data.json();

  return (
    <section className="holder">
      <h2>Novedades</h2>
      {novedades.map((item) => (
        <NovedadesItem
          key={NovedadesItem.id}
          title={item.titulo}
          subtitle={item.subtitulo}
          imagen={item.imagen}
          body={item.cuerpo}
        />
      ))}
    </section>
  );
}
