import "@/styles/nosotros.css";

export const metadata = {
  title: "Transportes x :: Nosotros",
  description: "destacadosGenerated by create next app",
};

export default function Nosotros() {
  return (
    <section className="holder">
      <div className="historia">
        <h2>Historia</h2>
        <div>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elite. Accusamus
            doloremque ducimus, eveniet harum illum incidunt ipsam laborum magni
            masitatibus nemo numquam em quod reiciendis velit.
          </p>

          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elite. Accusamus
            doloremque ducimus, eveniet harum illum incidunt ipsam laborum magni
            masitatibus nemo numquam em quod reiciendis velit.
          </p>
        </div>
      </div>
      <h2>Staff</h2>
      <div className="personas">
        <div className="persona">
          <img src="/images/nosotros/nosotros1.jpg" width="75" alt="imagen1" />
          <h5>Juan Gomez</h5>
          <h6>Gerente General</h6>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elite. Accusamus
            doloremque ducimus.
          </p>
        </div>

        <div className="persona">
          <img src="/images/nosotros/nosotros2.jpg" width="75" alt="imagen1" />
          <h5>Juan Gomez</h5>
          <h6>Gerente General</h6>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elite. Accusamus
            doloremque ducimus.
          </p>
        </div>

        <div className="persona">
          <img src="/images/nosotros/nosotros3.jpg" width="75" alt="imagen1" />
          <h5>Juan Gomez</h5>
          <h6>Gerente General</h6>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elite. Accusamus
            doloremque ducimus.
          </p>
        </div>

        <div className="persona">
          <img src="/images/nosotros/nosotros4.jpg" width="75" alt="imagen1" />
          <h5>Juan Gomez</h5>
          <h6>Gerente General</h6>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elite. Accusamus
            doloremque ducimus.
          </p>
        </div>

        <div className="persona">
          <img src="/images/nosotros/nosotros5.jpg" width="75" alt="imagen1" />
          <h5>Juan Gomez</h5>
          <h6>Gerente General</h6>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elite. Accusamus
            doloremque ducimus.
          </p>
        </div>
      </div>
    </section>
  );
}
