
import "@/styles/globals.css";
import Nav from "@/components/nav";
export const metadata = {
  title: "Transporte",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <header>
        <div className="holder">
          <div className="logo">
            <img src="/images/logo.png" width={100}
                alt="Transportes X" />
            <h1>Transportes X</h1>
            
          </div>
        </div>
      </header>
      <Nav/>
        {children}

        <footer>
          <p>Derechos reservados. Transportes X Año</p>
        </footer>
      </body>
    </html>
  );
}
